version: "1.0"
services:
    nginx:
        container_name: "nginx-sos"
        build: ./volumes/nginx
        ports:
            - "8081:80"
        volumes:
            - ./var/www:/var/www
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
        links:
            - php
    php:
        container_name: "php-sos"
        build: ./volumes/php
        ports:
            - "3306:3306"
        volumes:
            - ./var/www:/var/www
            - ./etc/supervisor/conf.d:/etc/supervisor/conf.d
        extra_hosts:
        - "host.docker.internal:host-gateway"
